import string
from Token import Token
from Examiner import Examiner
from CobolExaminer import CobolExaminer
from TokenBuilders import (
  InvalidTokenBuilder,
  WhitespaceTokenBuilder,
  NewlineTokenBuilder,
  StringTokenBuilder,
  PrefixedStringTokenBuilder,
  IntegerTokenBuilder,
  IntegerExponentTokenBuilder,
  RealTokenBuilder,
  RealExponentTokenBuilder,
  ListTokenBuilder,
  LeadCommentTokenBuilder,
  BlockTokenBuilder
)
from CobolTokenBuilders import (
  CobolIdentifierTokenBuilder,
  PictureTokenBuilder,
  CRPictureTokenBuilder,
  CobolPreprocessorTokenBuilder,
  AsteriskCommentTokenBuilder
)
from Tokenizer import Tokenizer

class Cobol2014Examiner(CobolExaminer):
  def __init__(self, code, extension):
    super().__init__()

    whitespace_tb = WhitespaceTokenBuilder()
    newline_tb = NewlineTokenBuilder()

    integer_tb = IntegerTokenBuilder(False)
    integer_exponent_tb = IntegerExponentTokenBuilder()
    real_tb = RealTokenBuilder(False, True)
    real_exponent_tb = RealExponentTokenBuilder(False, True, 'E')
    identifier_tb = CobolIdentifierTokenBuilder()
    string_tb = StringTokenBuilder(['"', "'"], True, False)
    n_string_tb = PrefixedStringTokenBuilder('N', False, ['"', "'"])
    nx_string_tb = PrefixedStringTokenBuilder('NX', False, ['"', "'"])
    picture_tb = PictureTokenBuilder()
    cr_picture_tb = CRPictureTokenBuilder()
    inline_comment_tb = LeadCommentTokenBuilder('*>')
    star_comment_tb = AsteriskCommentTokenBuilder()

    terminators = ['.']

    terminators_tb = ListTokenBuilder(terminators, 'statement terminator', False)

    known_operators = [
      'ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE',
      '+', '-', '*', '/', '**',
      '=', '<>', '>', '>=', '<', '<=',
      'AND', 'OR', 'NOT',
      'B-AND', 'B-NOT', 'B-OR', 'B-XOR',
      ':'
    ]

    known_operator_tb = ListTokenBuilder(known_operators, 'operator', True)

    self.unary_operators = [
      '+', '-', 'NOT'
    ]

    groupers = ['(', ')', ',']

    groupers_tb = ListTokenBuilder(groupers, 'group', False)

    keywords = [
      'ACCEPT', 'ACCESS',
      'ACTIVE-CLASS',
      'ADD', 'ADDRESS',
      'ADVANCING',
      'AFTER', 'ALIGNED',
      'ALL',
      'ALLOCATE',
      'ALPHABET',
      'ALPHABETIC', 'ALPHABETIC-LOWER', 'ALPHABETIC-UPPER',
      'ALPHANUMERIC', 'ALPHANUMERIC-EDITED',
      'ALSO',
      'ALTER', 'ALTERNATE', 'AND',
      'ANY', 'ANYCASE',
      'APPLY',
      'ARE', 'AREA', 'AREAS',
      'ARITHMETIC',
      'ASCENDING',
      'ASSIGN', 'AT',
      'AUTHOR',
      'AUTO',
      'AUTOMATIC',
      'AWAY-FROM-ZERO',
      'BACKGROUND-COLOR',
      'BASED',
      'BASIS',
      'BEFORE',
      'BEGINNING',
      'BELL',
      'BINARY',
      'BINARY-CHAR', 'BINARY-DOUBLE', 'BINARY-LONG',
      'BINARY-SHORT', 'BIT',
      'BLANK', 'BLINK', 'BLOCK',
      'BOOLEAN',
      'BOTTOM',
      'BY',
      'BYTE-LENGTH',
      'CALL', 'CANCEL',
      'CAPACITY',
      'CBL',
      'CD',
      'CENTER',
      'CF', 'CH', 'CHARACTER', 'CHARACTERS',
      'CLASS', 'CLASS-ID',
      'CLASSIFICATION',
      'CLOCK-UNITS', 'CLOSE', 'COBOL', 'CODE',
      'CODE-SET',
      'COL',
      'COLLATING',
      'COLS',
      'COLUMN',
      'COLUMNS',
      'COM-REG',
      'COMMA',
      'COMMON',
      'COMMUNICATION',
      'COMP',
      'COMPUTATIONAL',
      'COMPUTE', 'CONDITION', 'CONFIGURATION',
      'CONSTANT', 'CONTAINS',
      'CONTENT', 'CONTINUE',
      'CONTROL', 'CONTROLS',
      'CONVERTING',
      'COPY',
      'CORR', 'CORRESPONDING',
      'COUNT', 'CRT', 'CURRENCY', 'CURSOR',
      'CYCLE',
      'DATA', 'DATA-POINTER',
      'DATE', 'DATE-COMPILED', 'DATE-WRITTEN',
      'DAY', 'DAY-OF-WEEK',
      'DBCS',
      'DE', 'DEBUGGING', 'DEBUG-CONTENTS', 'DEBUG-ITEM', 'DEBUG-LINE', 'DEBUG-NAME',
      'DEBUG-SUB-1', 'DEBUG-SUB-2', 'DEBUG-SUB-3',
      'DEBUGGING',
      'DECIMAL-POINT', 'DECLARATIVES',
      'DELETE',
      'DELIMITED', 'DELIMITER',
      'DEPENDING', 'DESCENDING', 'DESTINATION',
      'DETAIL',
      'DISABLE',
      'DISPLAY', 'DISPLAY-1', 'DISPLAY-OF',
      'DIVIDE', 'DIVISION', 'DOWN',
      'DUPLICATES', 'DYNAMIC',
      'EC',
      'EGCS',
      'EGI',
      'EJECT',
      'ELSE',
      'EMI', 'ENABLE', 'END',
      'END-ACCEPT', 'END-ADD', 'END-CALL', 'END-COMPUTE', 'END-DELETE', 'END-DISPLAY',
      'END-DIVIDE', 'END-EVALUATE', 'END-IF',
      'END-INVOKE',
      'END-MULTIPLY',
      'END-OF-PAGE',
      'END-PERFORM', 'END-READ', 'END-RECEIVE', 'END-RETURN', 'END-REWRITE',
      'END-SEARCH', 'END-START', 'END-STRING', 'END-SUBTRACT', 'END-UNSTRING',
      'END-WRITE',
      'ENDING',
      'ENTER',
      'ENTRY-CONVENTION', 'ENTRY-FIELD',
      'ENVIRONMENT',
      'EO',
      'EOL', 'EOP', 'EOS',
      'EQUAL', 'ERASE', 'ERROR', 'ESI',
      'EVALUATE',
      'EVERY',
      'EXCEPTION', 'EXCEPTION-OBJECT',
      'EXCLUSIVE',
      'EXIT', 'EXPANDS', 'EXTEND',
      'EXTERN', 'EXTERNAL',
      'FACTORY',
      'FALSE',
      'FD', 'FILE', 'FILE-CONTROL',
      'FILLER', 'FINAL', 'FIRST',
      'FLOAT-BINARY-128', 'FLOAT-BINARY-32', 'FLOAT-BINARY-64',
      'FLOAT-DECIMAL-16', 'FLOAT-DECIMAL-34',
      'FLOAT-EXTENDED', 'FLOAT-INFINITY', 'FLOAT-LONG', 'FLOAT-NOT-A-NUMBER', 'FLOAT-SHORT',
      'FOOTING', 'FOR', 'FOREGROUND-COLOR', 'FOREVER', 'FORMAT', 'FREE', 'FROM', 'FULL',
      'FUNCTION', 'FUNCTION-ID', 'FUNCTION-POINTER',
      'GENERATE', 'GET', 'GIVING', 'GLOBAL', 'GO',
      'GOBACK',
      'GREATER', 'GROUP', 'GROUP-USAGE',
      'HEADING', 'HIGH-VALUE', 'HIGH-VALUES', 'HIGHLIGHT',
      'I-O', 'I-O-CONTROL',
      'IDENTIFICATION', 'IF',
      'IGNORING', 'IMPLEMENTS',
      'IN', 'INDEX', 'INDEXED',
      'INDICATE',
      'INHERITS',
      'INITIAL', 'INITIALIZE', 'INITIALIZED',
      'INITIATE', 'INPUT', 'INPUT-OUTPUT',
      'INSERT',
      'INSPECT',
      'INTERFACE', 'INTERFACE-ID',
      'INTERMEDIATE',
      'INSTALLATION', 'INTO', 'INTRINSIC', 'INVALID',
      'INVOKE',
      'IS',
      'JUST', 'JUSTIFIED',
      'KANJI',
      'KEY',
      'LABEL', 'LAST',
      'LC_ALL', 'LC_COLLATE', 'LC_CTYPE', 'LC_MESSAGES', 'LC_MONEY', 'LC_NUMERIC', 'LC_TIME',
      'LEADING', 'LEFT', 'LENGTH', 'LESS', 'LIMIT', 'LIMITS',
      'LINAGE', 'LINAGE-COUNTER',
      'LINE', 'LINE-COUNTER', 'LINES', 'LINKAGE',
      'LOCAL-STORAGE', 'LOCALE',
      'LOCK', 'LOW-VALUE', 'LOW-VALUES', 'LOWLIGHT',
      'MANUAL',
      'MEMORY', 'MERGE', 'MESSAGE',
      'METACLASS',
      'METHOD', 'METHOD-ID',
      'MINUS',
      'MODE', 'MODULES',
      'MORE-LABELS', 
      'MOVE', 'MULTIPLE', 'MULTIPLY',
      'NATIONAL', 'NATIONAL-EDITED', 'NATIONAL-OF',
      'NATIVE',
      'NATIVE_BINARY',
      'NEAREST-AWAY-FROM-ZERO', 'NEAREST-EVEN', 'NEAREST-TOWARD-ZERO',
      'NEGATIVE', 'NESTED', 'NEW', 'NEXT', 'NO',
      'NONE', 'NORMAL', 'NOT',
      'NULL', 'NULLS',
      'NUMBER', 'NUMBERS', 'NUMERIC', 'NUMERIC-EDITED',
      'OBJECT',
      'OBJECT-COMPUTER', 'OBJECT-REFERENCE', 'OCCURS', 'OF', 'OFF', 'OMITTED', 'ON',
      'ONLY', 'OPEN', 'OPTIONAL', 'OPTIONS', 'OR',
      'ORDER',
      'ORGANIZATION',
      'OTHER',
      'OUTPUT', 'OVERFLOW',
      'OVERRIDE',
      'PACKED-DECIMAL', 'PADDING',
      'PAGE', 'PAGE-COUNTER', 'PARAGRAPH',
      'PASSWORD',
      'PERFORM', 'PF', 'PH', 'PHYSICAL', 'PIC', 'PICTURE',
      'PLUS', 'POINTER', 'POSITION', 'POSITIVE',
      'PREFIXED', 'PRESENT', 'PREVIOUS',
      'PRINTING',
      'PROCEDURE', 'PROCEDURE-POINTER', 'PROCEDURES',
      'PROCEED',
      'PROCESSING',
      'PROGRAM', 'PROGRAM-ID', 'PROGRAM-POINTER',
      'PROHIBITED', 'PROPERTY', 'PROTOTYPE',
      'PURGE',
      'QUEUE', 'QUOTE', 'QUOTES',
      'RAISE', 'RAISING', 'RANDOM', 'RD', 'READ',
      'READY',
      'RECEIVE', 'RECORD',
      'RECORDS',
      'RECURSIVE',
      'REDEFINES', 'REEL', 'REFERENCE',
      'REFERENCES',
      'RELATION', 'RELATIVE', 'RELEASE',
      'RELOAD',
      'REMAINDER',
      'REMOVAL',
      'RENAMES', 'REPLACE', 'REPLACING', 'REPORT', 'REPORTING', 'REPORTS',
      'REPOSITORY', 'REQUIRED',
      'RERUN', 'RESERVE', 'RESET', 'RESUME', 'RETRY', 'RETURN',
      'RETURN-CODE', 'RETURNING',
      'REVERSED', 'REWIND', 'REWRITE',
      'RF', 'RH', 'RIGHT', 'ROUNDED', 'ROUNDING', 'RUN',
      'SAME', 'SD', 'SCREEN', 'SEARCH', 'SECONDS', 'SECTION', 'SECURE', 'SECURITY',
      'SEGMENT', 'SEGMENT-LIMIT', 'SELECT',
      'SELF',
      'SEND', 'SENTENCE',
      'SEPARATE',
      'SEQUENCE', 'SEQUENTIAL',
      'SERVICE',
      'SET',
      'SHARING',
      'SHIFT-IN', 'SHIFT-OUT',
      'SHORT',
      'SIGN', 'SIGNED', 'SIZE',
      'SKIP1', 'SKIP2', 'SKIP3',
      'SORT',
      'SORT-CONTROL', 'SORT-CORE-SIZE', 'SORT-FILE-SIZE',
      'SORT-MERGE',
      'SORT-MESSAGE', 'SORT-MODE-SIZE', 'SORT-RETURN',
      'SOURCE', 'SOURCE-COMPUTER', 'SOURCES', 'SPACE', 'SPACES', 'SPECIAL-NAMES',
      'STANDARD',
      'STANDARD-1', 'STANDARD-2', 'STANDARD-BINARY', 'STANDARD-DECIMAL',
      'START',
      'STATEMENT',
      'STATUS', 'STEP,' 'STOP', 'STRING', 'STRONG',
      'SUB-QUEUE-1', 'SUB-QUEUE-2', 'SUB-QUEUE-3',
      'SUBTRACT', 'SUM',
      'SUPER',
      'SUPPRESS', 'SYMBOL', 'SYMBOLIC', 'SYNC', 'SYNCHRONIZED',
      'SYSTEM-DEFAULT',
      'TABLE',
      'TALLY',
      'TALLYING',
      'TAPE', 'TERMINAL', 'TERMINATE', 'TEST',
      'TEXT', 'THAN', 'THEN', 'THROUGH', 'THRU', 'TIME', 'TIMES',
      'TITLE', 'TO',
      'TOP',
      'TOWARD-GREATER', 'TOWARD-LESSER',
      'TRACE',
      'TRAILING',
      'TRUE',
      'TRUNCATION',
      'TYPE', 'TYPEDEF',
      'UCS-4', 'UNDERLINE',
      'UNIT', 'UNIVERSAL', 'UNLOCK', 'UNSIGNED', 'UNSTRING',
      'UNTIL', 'UP', 'UPON', 'USAGE', 'USE', 'USER-DEFAULT', 'USING',
      'UTF-16', 'UTF-8',
      'VAL-STATUS', 'VALID', 'VALIDATE', 'VALIDATE-STATUS', 'VALUE', 'VALUES', 'VARYING',
      'WHEN',
      'WHEN-COMPILED',
      'WITH', 'WORDS', 'WORKING-STORAGE', 'WRITE',
      'WRITE-ONLY',
      'YYYYDDD', 'YYYYMMDD',
      'ZERO', 'ZEROES', 'ZEROS'
    ]

    acu_keywords = [
      '3-D',
      'ACTION',
      'ACTIVE-X',
      'ADJUSTABLE-COLUMNS',
      'ALIGNMENT',
      'AUTO-DECIMAL', 'AUTO-SPIN',
      'BACKGROUND-HIGH', 'BACKGROUND-LOW', 'BACKGROUND-STANDARD',
      'BAR',
      'BITMAP', 'BITMAP-END', 'BITMAP-HANDLE', 'BITMAP-NUMBER', 'BITMAP-START',
      'BITMAP-TRAILING', 'BITMAP-TRANSPARENT-COLOR', 'BITMAP-WIDTH',
      'BOX', 'BOXED', 'BUSY', 'BUTTONS',
      'CALENDAR-FONT',
      'CANCEL-BUTTON',
      'CELL', 'CELL-COLOR', 'CELL-DATA', 'CELL-FONT', 'CELL-PROTECTION',
      'CENTERED-HEADING',
      'CENTURY-DATE',
      'CHECK-BOX',
      'CLEAR-SELECTION', 'CLINE', 'CLINES',
      'COLORS',
      'COLUMN-COLOR', 'COLUMN-DIVIDERS', 'COLUMN-FONT', 'COLUMN-HEADINGS',
      'COLUMN-PROTECTION',
      'COMBO-BOX',
      'COPY-SELECTION',
      'CSIZE',
      'CURSOR-COL', 'CURSOR-COLOR', 'CURSOR-FRAME-WIDTH', 'CURSOR-ROW',
      'CURSOR-X', 'CURSOR-Y', 'CUSTOM-PRINT-TEMPLATE',
      'DASHED',
      'DATA-COLUMNS', 'DATA-TYPES',
      'DATE-ENTRY',
      'DEFAULT-BUTTON', 'DEFAULT-FONT',
      'DESTROY',
      'DISPLAY-COLUMNS', 'DISPLAY-FORMAT',
      'DOTDASH', 'DOTTED', 'DOUBLE',
      'DRAG-COLOR', 'DROP-DOWN', 'DROP-LIST',
      'END-COLOR', 'END-MODIFY',
      'ENGRAVED', 'ENSURE-VISIBLE',
      'ENTRY-FIELD', 'ENTRY-REASON', 'ESCAPE-BUTTON',
      'EVENT', 'EVENT-LIST', 'EXCEPTION-VALUE',
      'EXPAND', 'EXTERNAL-FORM',
      'FILE-NAME', 'FILE-POS',
      'FILL-COLOR', 'FILL-COLOR-2', 'FILL-PERCENT',
      'FINISH-REASON',
      'FIXED-FONT', 'FIXED-WIDTH', 'FLAT', 'FLAT-BUTTONS',
      'FLOAT', 'FLOATING', 'FONT', 'FRAME', 'FRAMED', 'FULL-HEIGHT',
      'GO-BACK', 'GO-FORWARD', 'GO-HOME', 'GO-SEARCH',
      'GRAPHICAL', 'GRID', 'GROUP-VALUE',
      'HANDLE', 'HAS-CHILDREN', 'HEADING-COLOR', 'HEADING-DIVIDER-COLOR',
      'HEADING-FONT',
      'HEAVY', 'HEIGHT-IN-CELLS', 'HIDDEN-DATA',
      'HIGH-COLOR', 'HOT-TRACK', 'HSCROLL', 'HSCROLL-POS',
      'ICON', 'IDENTIFIED', 'INDEPENDENT', 'INQUIRE',
      'INSERTION-INDEX', 'INSERTION-ROWS',  'ITEM', 'ITEM-TEXT', 'ITEM-TO-ADD',
      'ITEM-TO-DELETE', 'ITEM-TO-EMPTY', 'ITEM-VALUE',
      'LABEL', 'LABEL-OFFSET', 'LARGE-FONT', 'LARGE-OFFSET',
      'LAST-ROW', 'LAYOUT-DATA', 'LAYOUT-MANAGER', 'LEADING-SHIFT',
      'LEFT-TEXT', 'LINES-AT-ROOT', 'LIST-BOX', 'LM-RESIZE',
      'LONG-DATE', 'LOW-COLOR', 'LOWERED',
      'MASS-UPDATE', 'MAX-LINES', 'MAX-PROGRESS', 'MAX-TEXT', 'MAX-VAL',
      'MEDIUM-FONT', 'MENU', 'MIN-VAL', 'MODIFY', 'MULTILINE',
      'NAVIGATE-URL', 'NEXT-ITEM', 'NO-AUTOSEL', 'NO-AUTO-DEFAULT', 'NO-BOX',
      'NO-DIVIDERS', 'NO-F4', 'NO-FOCUS', 'NO-GROUP-TAB',
      'NO-KEY-LETTER', 'NO-SEARCH', 'NO-UPDOWN', 'NOTAB',
      'NOTIFY', 'NOTIFY-CHANGE', 'NOTIFY-DBLCLICK', 'NOTIFY-SELCHANGE',
      'NUM-COL-HEADINGS', 'NUM-ROWS',
      'OK-BUTTON', 'OVERLAP-LEFT', 'OVERLAP-TOP',
      'PAGE-SETUP', 'PAGED', 'PARENT', 'PERMANENT', 'PIXEL',
      'PLACEMENT', 'POP-UP', 'POSITION-SHIFT', 'PRINT-NO-PROMPT', 'PRINT-PREVIEW',
      'PRIORITY', 'PROGRESS', 'PROPERTIES', 'PROPERTY', 'PUSH-BUTTON',
      'QUERY-INDEX',
      'RADIO-BUTTON', 'RAISED', 'READ-ONLY',
      'RECORD-DATA', 'RECORD-TO-ADD', 'RECORD-TO-DELETE', 'REFRESH',
      'REGION-COLOR', 'RESET-GRID', 'RESET-LIST', 'RESET-TABS',
      'RIGHT-ALIGN', 'RIMMED', 'ROW-COLOR', 'ROW-COLOR-PATTERN',
      'ROW-DIVIDERS', 'ROW-FONT', 'ROW-HEADINGS', 'ROW-PROTECTION',
      'SAVE-AS', 'SAVE-AS-NO-PROMPT', 'SCROLL-BAR', 'SEARCH-OPTIONS', 'SEARCH-TEXT',
      'SELECT-ALL', 'SELECTION-INDEX', 'SELECTION-TEXT', 'SELF-ACT',
      'SEPARATION', 'SHADING', 'SHADOW', 'SHORT-DATE', 'SHOW-LINES',
      'SHOW-NONE', 'SHOW-SEL-ALWAYS', 'SMALL-FONT', 'SORT-ORDER',
      'SPINNER', 'SQUARE', 'START-X', 'START-Y', 'STATIC-LIST', 'STATUS-BAR', 'STATUS-TEXT',
      'STYLE', 'SUBWINDOW', 'TAB-TO-ADD', 'TAB-TO-DELETE',
      'TEMPORARY', 'TERMINATION-VALUE', 'THREAD', 'THREADS', 'THUMB-POSITION',
      'TILED-HEADINGS', 'TITLE', 'TITLE-POSITION', 'TRADITIONAL-FONT',
      'TRAILING-SHIFT', 'TRANSPARENT', 'TREE-VIEW',
      'UNFRAMED', 'UNSORTED', 'USE-ALT', 'USE-RETURN', 'USE TAB',
      'VALUE-FORMAT', 'VARIANT', 'VERTICAL', 'VERY-HEAVY',
      'VIRTUAL-WIDTH', 'VPADDING', 'VSCROLL', 'VSCROLL-BAR', 'VSCROLL-POS', 'VTOP',
      'WEB-BROWSER', 'WIDTH', 'WIDTH-IN-CELLS', 'WINDOW', 'X', 'Y'
    ]

    if extension.lower() == 'acu':
      keywords += acu_keywords

    keyword_tb = ListTokenBuilder(keywords, 'keyword', False)

    cobol_preprocessor_tb = CobolPreprocessorTokenBuilder()

    exec_tb = BlockTokenBuilder('EXEC', 'END-EXEC', 'exec block')

    invalid_token_builder = InvalidTokenBuilder()

    tokenbuilders = [
      whitespace_tb,
      newline_tb,
      terminators_tb,
      integer_tb,
      integer_exponent_tb,
      real_tb,
      real_exponent_tb,
      picture_tb,
      cr_picture_tb,
      keyword_tb,
      known_operator_tb,
      groupers_tb,
      identifier_tb,
      string_tb,
      n_string_tb,
      nx_string_tb,
      inline_comment_tb,
      star_comment_tb,
      cobol_preprocessor_tb,
      exec_tb,
      self.unknown_operator_tb,
      invalid_token_builder
    ]

    tokenizer = Tokenizer(tokenbuilders)
    self.tokens += tokenizer.tokenize(code)

    expected_keyword_confidence = self.CheckExpectedKeywords()

    self.calc_token_confidence()
    self.calc_operator_confidence()
    self.calc_operator_2_confidence()
    # self.calc_operator_3_confidence()
    # self.calc_operand_confidence()
    self.calc_keyword_confidence()
    self.calc_picture_confidence()
    self.confidences['expected_keywords'] = expected_keyword_confidence
