import string
from Examiner import Examiner
from TokenBuilders import (
  InvalidTokenBuilder,
  WhitespaceTokenBuilder,
  NewlineTokenBuilder,
  StringTokenBuilder,
  IdentifierTokenBuilder,
  IntegerTokenBuilder,
  IntegerExponentTokenBuilder,
  RealTokenBuilder,
  RealExponentTokenBuilder,
  ListTokenBuilder,
  PrefixedIntegerTokenBuilder,
  LeadCommentTokenBuilder
)
# from SqlTokenBuilders import ()
from Tokenizer import Tokenizer

class Sql2016Examiner(Examiner):
  def __init__(self, code):
    super().__init__()

    whitespace_tb = WhitespaceTokenBuilder()
    newline_tb = NewlineTokenBuilder()

    integer_tb = IntegerTokenBuilder(False)
    integer_exponent_tb = IntegerExponentTokenBuilder()
    real_tb = RealTokenBuilder(True, True)
    real_exponent_tb = RealExponentTokenBuilder(True, True, 'E')
    string_tb = StringTokenBuilder(["'", '"'], True, False)
    identifier_tb = IdentifierTokenBuilder()

    terminators = [';']

    terminators_tb = ListTokenBuilder(terminators, 'statement terminator', False)

    known_operators = [
      '=', '>', '>=', '<', '<=', '<>', '!=',
      'AND', 'OR', 'NOT',
      'IN', 'EXISTS', 'LIKE', 'BETWEEN', 'ANY', 'ALL'
    ]

    known_operator_tb = ListTokenBuilder(known_operators, 'operator', True)

    self.unary_operators = [
      'NOT', 'EXISTS', 'ANY', 'ALL'
    ]

    groupers = ['(', ')', ',']

    groupers_tb = ListTokenBuilder(groupers, 'group', False)

    keywords = [
      'ABS',
      'ACOS',
      'ALL', 'ALLOCATE', 'ALTER', 'AND', 'ANY', 'ARE',
      'ARRAY',
      'ARRAY_AGG',
      'ARRAY_MAX_CARDINALITY',
      'AS',
      'ASENSITIVE',
      'ASIN',
      'ASYMMETRIC',
      'AT',
      'ATAN',
      'ATOMIC',
      'AUTHORIZATION',
      'AVG',
      'BEGIN',
      'BEGIN_FRAME', 'BEGIN_PARTITION',
      'BETWEEN',
      'BIGINT',
      'BINARY',
      'BLOB', 'BOOLEAN',
      'BOTH',
      'BY',
      'CALL',
      'CALLED',
      'CARDINALITY',
      'CASCADED', 'CASE', 'CAST',
      'CEIL', 'CEILING',
      'CHAR',
      'CHAR_LENGTH',
      'CHARACTER',
      'CHARACTER_LENGTH',
      'CHECK',
      'CLASSIFIER',
      'CLOB',
      'COALESCE',
      'COLLATE',
      'COLUMN', 'COMMIT', 'CONDITION', 'CONNECT',
      'CONSTRAINT',
      'CONTAINS',
      'CONVERT',
      'CORR',
      'CORRESPONDING',
      'COS', 'COSH',
      'COUNT',
      'COVAR_POP', 'COVAR_SAMPLE',
      'CREATE', 'CROSS',
      'CUBE',
      'CUME_DIST',
      'CURRENT',
      'CURRENT_CATALOG',
      'CURRENT_DATE',
      'CURRENT_DEFAULT_TRANSFORM_GROUP',
      'CURRENT_PATH',
      'CURRENT_ROLE',
      'CURRENT_SCHEMA',
      'CURRENT_TIME', 'CURRENT_TIMESTAMP',
      'CURRENT_TRANSFORM_GROUP_FOR_TYPE',
      'CURRENT_USER', 'CURSOR',
      'CYCLE',
      'DATE', 'DAY', 'DEALLOCATE', 'DEC',
      'DECFLOAT',
      'DECIMAL', 'DECLARE', 'DEFAULT',
      'DEFINE',
      'DELETE',
      'DENSE_RANK',
      'DESCRIBE',
      'DETERMINISTIC',
      'DISCONNECT', 'DISTINCT',
      'DO',
      'DOUBLE', 'DROP',
      'DYNAMIC',
      'EACH',
      'ELEMENT',
      'ELSE',
      'ELSEIF',
      'EMPTY',
      'END',
      'END_EXEC',
      'EQUALS',
      'ESCAPE',
      'EVERY',
      'EXCEPT',
      'EXEC', 'EXECUTE', 'EXISTS',
      'EXP',
      'EXTERNAL',
      'EXTRACT',
      'FALSE', 'FETCH',
      'FILTER',
      'FIRST_VALUE',
      'FLOAT', 'FOR', 'FOREIGN',
      'FRAME_ROW',
      'FREE',
      'FROM', 'FULL', 'FUNCTION',
      'GET', 'GLOBAL',
      'GRANT', 'GROUP',
      'GROUPING',
      'GROUPS',
      'HANDLER', 'HAVING',
      'HOLD',
      'HOUR',
      'IDENTITY',
      'IF',
      'IN', 'INDICATOR',
      'INITIAL',
      'INNER', 'INOUT',
      'INSENSITIVE', 'INSERT',
      'INT', 'INTEGER', 'INTERSECT',
      'INTERSECTION',
      'INTERVAL', 'INTO', 'IS',
      'ITERATE',
      'JOIN',
      'JSON_ARRY', 'JSON_ARRAYAGG', 'JSON_EXISTS', 'JSON_OBJECT',
      'JSON_OBJECTAGG', 'JSON_QUERY', 'JSON_TABLE', 'JSON_TABLE_PRIMITIVE',
      'JSON_VALUE',
      'LAG',
      'LANGUAGE',
      'LARGE',
      'LAST_VALUE',
      'LATERAL',
      'LEAD',
      'LEADING',
      'LEAVE',
      'LEFT', 'LEVEL', 'LIKE',
      'LIKE_REGEX',
      'LISTAGG',
      'LN',
      'LOCAL',
      'LOCALTIME', 'LOCALTIMESTAMP',
      'LOG', 'LOG10',
      'LOOP',
      'LOWER',
      'MAP',
      'MATCH',
      'MATCH_NUMBER', 'MATCH_RECOGNIZE', 'MATCHES',
      'MAX',
      'MEMBER', 'MERGE',
      'METHOD',
      'MIN',
      'MINUTE',
      'MOD',
      'MODIFIES',
      'MODULE', 'MONTH',
      'MULTISET',
      'NATIONAL', 'NATURAL', 'NCHAR',
      'NCLOB', 'NEW',
      'NO',
      'NONE',
      'NORMALIZE',
      'NOT',
      'NTH_VALUE', 'NTILE',
      'NULL',
      'NULLIF',
      'NUMERIC',
      'OCCURRENCES_REGEX',
      'OCTET_LENGTH',
      'OF',
      'OFFSET',
      'OLD',
      'OMIT',
      'ON',
      'ONE',
      'ONLY', 'OPEN',
      'OR', 'ORDER',
      'OUT', 'OUTER',
      'OVER',
      'OVERLAPS',
      'OVERLAY',
      'PARAMETER',
      'PARTITION',
      'PATTERN', 'PER',
      'PERCENT',
      'PERCENT_RANK', 'PERCENTILE_CONT', 'PERCENTILE_DISC',
      'PERIOD', 'PORTION',
      'POSITION',
      'POSITION_REGEX', 'POWER',
      'PRECEDES',
      'PRECISION',
      'PREPARE',
      'PRIMARY',
      'PROCEDURE',
      'PTF',
      'RANGE',
      'RANK',
      'READS',
      'REAL',
      'RECURSIVE', 'REF',
      'REFERENCES',
      'REFERENCING',
      'REGR_AVGX', 'REGR_AVGY', 'REGR_COUNT', 'REGR_INTERCEPT', 'REGR_R2',
      'REGR_SLOPE', 'REGR_SXX', 'REGR_SXY', 'REGR_SYY',
      'RELEASE', 'REPEAT', 'REGIONAL',
      'RESULT',
      'RETURN', 'RETURNS', 'REVOKE', 'RIGHT',
      'ROLLBACK',
      'ROLLUP',
      'ROW',
      'ROW_NUMBER',
      'ROWS',
      'RUNNING',
      'SAVEPOINT',
      'SCOPE',
      'SCROLL',
      'SEARCH',
      'SECOND',
      'SEEK',
      'SELECT',
      'SENSITIVE',
      'SESSION_USER', 'SET',
      'SHOW',
      'SIMILAR',
      'SIN', 'SINH',
      'SMALLINT', 'SOME',
      'SPECIFIC',
      'SPECIFICTYPE',
      'SQL',
      'SQLEXCEPTION', 'SQLSTATE', 'SQLWARNING',
      'SQRT',
      'START',
      'STATIC',
      'STDDEV_POP', 'STDDEV_SAMP',
      'SUBMULTISET',
      'SUBSET',
      'SUBSTRING',
      'SUBSTRING_REGEX',
      'SUM',
      'SYMMETRIC', 'SYSTEM',
      'SYSTEM_USER',
      'TABLE',
      'TABLESAMPLE',
      'TAN', 'TANH',
      'THEN', 'TIME', 'TIMESTAMP', 'TIMEZONE_HOUR',
      'TIMEZONE_MINUTE', 'TO', 'TRAILING',
      'TRANSLATE',
      'TRANSLATE_REGEX',
      'TRANSLATION',
      'TREAT', 'TRIGGER',
      'TRIM',
      'TRIM_ARRAY',
      'TRUE',
      'TRUNCATE',
      'UESCAPE',
      'UNION', 'UNIQUE', 'UNKNOWN',
      'UNNEST', 'UNTIL',
      'UPDATE',
      'UPPER',
      'USER', 'USING',
      'VALUE', 'VALUES',
      'VALUE_OF',
      'VAR_POP', 'VAR_SAMP',
      'VARCHAR', 'VARYING',
      'VERSIONING',
      'VIEW',
      'WHEN', 'WHENEVER', 'WHERE',
      'WHILE',
      'WIDTH_BUCKET',
      'WINDOW',
      'WITH',
      'WITHIN', 'WITHOUT',
      'YEAR'
    ]

    keyword_tb = ListTokenBuilder(keywords, 'keyword', False)

    invalid_token_builder = InvalidTokenBuilder()

    tokenbuilders = [
      whitespace_tb,
      newline_tb,
      integer_tb,
      integer_exponent_tb,
      real_tb,
      real_exponent_tb,
      string_tb,
      known_operator_tb,
      terminators_tb,
      groupers_tb,
      keyword_tb,
      identifier_tb,
      self.unknown_operator_tb,
      invalid_token_builder
    ]

    tokenizer = Tokenizer(tokenbuilders)
    self.tokens = tokenizer.tokenize(code)

    self.calc_token_confidence()
    self.calc_operator_confidence()
    self.calc_operator_2_confidence()
    self.calc_operator_3_confidence()
    # self.calc_operand_confidence()
    self.calc_keyword_confidence()
